# Generated by Django 5.2 on 2025-10-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0013_alter_client_requires_note_for_credit_and_more'),
        ('orders', '0010_rename_employee_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='billing_files/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Facturasciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BillingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('partially_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to='orders.order')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingrecord')),
            ],
            options={
                'verbose_name': 'Venta de Facturación',
                'verbose_name_plural': 'Ventas de Facturación',
                'ordering': ['-payment_date'],
            },
        ),
    ]
