# Generated by Django 5.2 on 2025-10-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrecord_identifier'),
        ('orders', '0012_fix_order_status_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingorder',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Agregar venta a factura', 'verbose_name_plural': 'Agregar ventas a factura'},
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto pagado'),
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pagado Totalmente'),
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to='orders.order', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='partially_paid',
            field=models.BooleanField(default=False, verbose_name='Pago parcial'),
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
