# Generated by Django 5.2 on 2025-11-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Facturación', 'verbose_name_plural': 'Facturas Emitidas'},
        ),
    ]
