# Generated by Django 5.2 on 2025-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billingrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serie'),
        ),
    ]
