# Generated by Django 5.2 on 2025-12-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingrecord_folio'),
        ('clients', '0020_remove_address_clients_address_city_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='emmited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='clients.client', verbose_name='Cliente'),
        ),
    ]
