# Generated by Django 5.2 on 2025-12-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingrecord_emmited_at_alter_billingrecord_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agregar venta a factura', 'verbose_name_plural': 'Agregar ventas a factura'},
        ),
        migrations.RemoveField(
            model_name='billingorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='billingorder',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='billingorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='billing_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to='billing.billingrecord', verbose_name='Registro de Facturación'),
        ),
    ]
