# Generated by Django 5.2 on 2026-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_billingorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingFrequencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Frecuencia de Facturación',
                'verbose_name_plural': 'Reportes de Frecuencia de Facturación',
                'permissions': [('view_billing_frequency_report', 'Can view billing frequency report')],
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
