# Generated by Django 5.2 on 2026-02-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_clientbillingfrecuency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='frequency',
            field=models.CharField(choices=[('when_delivery', 'Contra entrega'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='other', max_length=50, verbose_name='Frecuencia de Facturación'),
        ),
    ]
