# Generated by Django 5.2 on 2026-04-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_rename_billingrecord_to_invoice_billingorder_to_invoiceorderlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas Emitidas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceorderlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venta en factura', 'verbose_name_plural': 'Ventas en factura'},
        ),
    ]
