# Generated by Django 5.2 on 2025-09-25 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('street_number', models.CharField(max_length=255)),
                ('city', models.CharField(default='Queretaro', max_length=100)),
                ('state', models.CharField(default='Queretaro', max_length=100)),
                ('zip_code', models.CharField(default='76000', max_length=20)),
                ('position', models.CharField(blank=True, choices=[('manager', 'Administrador'), ('driver', 'Chofer'), ('staff', 'Ventas')], max_length=100, null=True)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
