# Generated by Django 5.2 on 2025-10-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('full_time', 'Tiempo Completo'), ('part_time', 'Tiempo Parcial'), ('contract', 'Contrato')], default='full_time', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Chofer Asignado'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='capacity_liters',
            field=models.PositiveIntegerField(verbose_name='Capacidad (litros)'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
    ]
