# Generated by Django 5.2 on 2025-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_apellidos_employee_nombre_employee_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Queretaro', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('manager', 'Administrador'), ('driver', 'Chofer'), ('staff', 'Ventas')], max_length=100, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(default='Queretaro', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_number',
            field=models.CharField(max_length=255, verbose_name='Calle y Número'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(default='76000', max_length=20, verbose_name='Código Postal'),
        ),
    ]
