# Generated by Django 5.2 on 2026-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_city_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Día Festivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Día No Laborable',
                'verbose_name_plural': 'Días No Laborables',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='core_nonwor_date_e1827e_idx'), models.Index(fields=['is_active', 'date'], name='core_nonwor_is_acti_fa95e9_idx')],
            },
        ),
    ]
