# Generated by Django 5.2 on 2025-09-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('presentation', models.CharField(help_text='Garrafon, Botella, Caja', max_length=200)),
                ('unit_of_measure', models.IntegerField(choices=[(0, 'not applicable'), (1, 'lt'), (2, 'ml'), (3, 'm'), (4, 'pulg'), (6, 'cm'), (7, 'mg'), (8, 'kg'), (9, 'g'), (5, 'pieza')], default=0)),
                ('image', models.FileField(blank=True, null=True, upload_to='product_images/')),
                ('order', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('min_inventory', models.IntegerField(default=0, help_text='Minimum inventory quantity')),
                ('max_inventory', models.IntegerField(default=0, help_text='Maximum inventory quantity')),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productcategory')),
            ],
            options={
                'ordering': ['order'],
                'permissions': [('min_max_inventory', 'Can control min max inventory quantity')],
            },
        ),
        migrations.CreateModel(
            name='ProductClientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
                ('until_date', models.DateField(blank=True, help_text='Fecha hasta la cual es valido este precio, dejar en blanco para que sea indefinido', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product prices',
                'unique_together': {('product', 'client')},
            },
        ),
    ]
