# Generated by Django 5.2 on 2025-09-24 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_address_city_alter_address_state_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclientprice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='clients.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='productclientprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='product'),
        ),
    ]
