# Generated by Django 5.2 on 2025-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productclientprice_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'permissions': [('min_max_inventory', 'Can control min max inventory quantity')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productclientprice',
            options={'verbose_name_plural': 'Precios de productos'},
        ),
    ]
