# Generated by Django 5.2 on 2025-10-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_add_balance_credit_history'),
        ('product', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_inventory',
            field=models.IntegerField(default=0, help_text='Maximum inventory quantity', verbose_name='Cantidad máxima en inventario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_inventory',
            field=models.IntegerField(default=0, help_text='Minimum inventory quantity', verbose_name='Cantidad mínima en inventario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(help_text='20, 1, 500', max_length=200, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.IntegerField(choices=[(0, 'not applicable'), (1, 'lt'), (2, 'ml'), (3, 'm'), (4, 'pulg'), (6, 'cm'), (7, 'mg'), (8, 'kg'), (9, 'g'), (5, 'pieza')], default=0, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='productclientprice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='productclientprice',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='productclientprice',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productclientprice',
            name='until_date',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual es valido este precio, dejar en blanco para que sea indefinido', null=True, verbose_name='Fecha de Validez'),
        ),
    ]
