# Generated by Django 5.2 on 2026-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('min_max_inventory', 'Can control min max inventory quantity')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productclientprice',
            options={'verbose_name_plural': 'Precios de productos por cliente'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, help_text='Precio base del producto, se puede sobreescribir por cliente en la sección de clientes', verbose_name='Precio base'),
        ),
    ]
