# Generated by Django 5.2 on 2026-02-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'presentation', 'unit_of_measure')},
        ),
    ]
