# Generated by Django 5.2 on 2026-02-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_name_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclientprice',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
