# Generated by Django 5.2 on 2026-03-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productclientprice_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
    ]
