# Generated by Codex on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_created_at_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclientprice',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
