# Generated by Codex on 2026-09-07

from django.db import migrations
from django.db.models import Q


def set_garrafon_product_client_price_order(apps, schema_editor) -> None:
    ProductClientPrice = apps.get_model('product', 'ProductClientPrice')

    ProductClientPrice.objects.filter(orden__isnull=True).filter(
        Q(product__name__icontains='garrafon')
        | Q(product__name__icontains='garrafón')
        | Q(product__category__name__icontains='garrafon')
        | Q(product__category__name__icontains='garrafón')
    ).update(orden=1)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productclientprice_orden'),
    ]

    operations = [
        migrations.RunPython(
            set_garrafon_product_client_price_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
