# Generated by Codex on 2026-09-08

from django.db import migrations, models
from django.db.models import Min, Q


def move_client_price_order_to_product(apps, schema_editor) -> None:
    Product = apps.get_model('product', 'Product')
    ProductClientPrice = apps.get_model('product', 'ProductClientPrice')

    product_orders = (
        ProductClientPrice.objects.filter(orden__isnull=False)
        .values('product_id')
        .annotate(product_order=Min('orden'))
    )

    for row in product_orders:
        Product.objects.filter(pk=row['product_id']).update(orden=row['product_order'])

    Product.objects.filter(
        Q(name__icontains='garrafon')
        | Q(name__icontains='garrafón')
        | Q(category__name__icontains='garrafon')
        | Q(category__name__icontains='garrafón')
    ).update(orden=1)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_backfill_garrafon_productclientprice_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.RunPython(
            move_client_price_order_to_product,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='productclientprice',
            name='orden',
        ),
    ]
