# Generated by Django 5.2 on 2025-09-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('pending', 'Pendiente'), ('failed', 'Fallido')], default='completed', max_length=20),
        ),
    ]
