# Generated by Django 5.2 on 2025-10-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_balance_client_credit_limit_and_more'),
        ('orders', '0007_alter_order_options'),
        ('payment', '0002_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='balance_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto pagado usando saldo del cliente', max_digits=10, verbose_name='Saldo Utilizado'),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto pagado usando crédito del cliente', max_digits=10, verbose_name='Crédito Utilizado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('cash', 'Efectivo'), ('balance', 'Saldo'), ('paypal', 'PayPal'), ('credit', 'Crédito'), ('bank_transfer', 'Transferencia Bancaria')], max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('pending', 'Pendiente'), ('failed', 'Fallido')], default='completed', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='payment_client_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payment_method_idx'),
        ),
    ]
