# Generated by Django 5.2 on 2026-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_created_at_payment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('cash', 'Efectivo'), ('balance', 'Saldo'), ('paypal', 'PayPal'), ('pending_credit', 'Crédito Pendiente'), ('bank_transfer', 'Transferencia Bancaria')], max_length=50, verbose_name='Método de Pago'),
        ),
    ]
