# Generated by Django 5.2 on 2026-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('pending', 'Pendiente'), ('failed', 'Fallido'), ('reversed', 'Revertido')], default='completed', max_length=20, verbose_name='Estado del Pago'),
        ),
    ]
