# Generated by Django 5.2 on 2026-01-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0021_alter_clientbillingfrecuency_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_reminder_days', models.PositiveIntegerField(default=10, help_text='Días antes del vencimiento para el primer recordatorio')),
                ('first_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('first_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('second_reminder_days', models.PositiveIntegerField(default=5, help_text='Días antes del vencimiento para la segunda notificación')),
                ('second_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('second_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('cancellation_days', models.PositiveIntegerField(default=0, help_text='Días después del vencimiento para la cancelación del servicio')),
                ('cancellation_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('cancellation_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_notification_setting', to='clients.client')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación de Facturación',
                'verbose_name_plural': 'Configuraciones de Notificaciones de Facturación',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('reminder', 'Recordatorio'), ('billing_soft_alert', '1era Notificación'), ('billing_hard_alert', '2da Notificación'), ('service_cancellation', 'Cancelación de Servicio')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notification.notification')),
            ],
            options={
                'verbose_name': 'Registro de Notificación',
                'verbose_name_plural': 'Registros de Notificaciones',
            },
        ),
    ]
