# Generated by Django 5.2 on 2026-01-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingnotificationsetting',
            name='cancellation_condition',
            field=models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingnotificationsetting',
            name='first_condition',
            field=models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingnotificationsetting',
            name='second_condition',
            field=models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50),
        ),
    ]
