# Generated by Django 5.2 on 2026-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_billingnotificationsetting_cancellation_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], default='sent', max_length=20),
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
