# Generated by Django 5.2 on 2026-01-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_clientbillingfrecuency_frequency_and_more'),
        ('notification', '0004_alter_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_reminder_days', models.PositiveIntegerField(default=10, help_text='Días antes del vencimiento para el primer recordatorio')),
                ('first_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('first_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('second_reminder_days', models.PositiveIntegerField(default=5, help_text='Días antes del vencimiento para la segunda notificación')),
                ('second_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('second_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('cancellation_days', models.PositiveIntegerField(default=0, help_text='Días después del vencimiento para la cancelación del servicio')),
                ('cancellation_condition', models.CharField(choices=[('billing_sent', 'Envio de Facturación'), ('credit_days', 'Venceimiento de Días de Crédito'), ('last_notification_sent', 'Última Notificación Enviada')], default='credit_days', help_text='Condición para enviar notificaciones de facturación', max_length=50)),
                ('cancellation_moment', models.CharField(choices=[('before', 'Antes'), ('after', 'Después')], default='after', help_text='Momento para enviar notificaciones de facturación', max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='clients.client')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación de cliente',
                'verbose_name_plural': 'Configuraciones de Notificaciones de cliente',
            },
        ),
        migrations.DeleteModel(
            name='BillingNotificationSetting',
        ),
    ]
