# Generated by Django 5.2 on 2026-09-29 15:27

import django.db.models.deletion
import route_confirmations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0012_replace_routeclient_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(verbose_name='Fecha de visita')),
                ('status', models.CharField(choices=[('Enviada', 'Enviada'), ('Confirmada', 'Confirmada'), ('NO visitar', 'NO visitar')], default='Enviada', max_length=20, verbose_name='Estatus')),
                ('token', models.CharField(db_index=True, default=route_confirmations.models.generate_confirmation_token, max_length=128, unique=True, verbose_name='Token')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido')),
                ('public_response_action', models.CharField(blank=True, choices=[('confirmar', 'Confirmar'), ('no-visitar', 'No visitar')], max_length=20, null=True, verbose_name='Acción pública')),
                ('override_note', models.TextField(blank=True, verbose_name='Nota de ajuste')),
                ('receipt_log', models.JSONField(blank=True, default=list, verbose_name='Recibos')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_visit_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('route_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_confirmations', to='routes.routeclient', verbose_name='Cliente en ruta')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_visit_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Confirmación de visita',
                'verbose_name_plural': 'Confirmaciones de visita',
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['route_client', 'visit_date'], name='route_confirm_client_date_idx'), models.Index(fields=['visit_date'], name='route_confirm_visit_date_idx'), models.Index(fields=['status'], name='route_confirm_status_idx'), models.Index(fields=['expires_at'], name='route_confirm_expires_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('route_client', 'visit_date'), name='route_confirm_active_visit_uniq')],
            },
        ),
    ]
