# Generated by Django 5.2 on 2026-09-28 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0049_credittransaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('urgent', models.BooleanField(default=False, verbose_name='Urgente')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='clients.client', verbose_name='Cliente')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-urgent', 'reminder_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['created_by', 'completed_at'], name='rem_user_done_idx'), models.Index(fields=['reminder_date'], name='rem_date_idx'), models.Index(fields=['urgent'], name='rem_urgent_idx')],
            },
        ),
    ]
