# Generated by Django 5.2 on 2025-09-25 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_billingdata_rfc_alter_client_name_and_more'),
        ('core', '0002_employee_delete_user'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_routes', to='clients.client')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_clients', to='routes.route')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('route', 'client')},
            },
        ),
        migrations.CreateModel(
            name='RouteEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_routes', to='core.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_employees', to='routes.route')),
            ],
            options={
                'unique_together': {('route', 'employee')},
            },
        ),
    ]
