# Generated by Django 5.2 on 2025-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routeclient_routeemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeclient',
            name='day_to_visit',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=50),
        ),
        migrations.AddField(
            model_name='routeclient',
            name='frecuency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=50),
        ),
    ]
