# Generated by Django 5.2 on 2025-09-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_update_billing_frequency_structure'),
        ('core', '0003_transport'),
        ('orders', '0006_alter_order_order_date_alter_order_status_and_more'),
        ('routes', '0003_routeclient_day_to_visit_routeclient_frecuency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of visit in the route')),
                ('visit_date', models.DateField(help_text='Specific date this order should be visited')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='routeemployee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routeemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='routeemployee',
            name='route',
        ),
        migrations.RenameField(
            model_name='routeclient',
            old_name='frecuency',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='routeclient',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='routeclient',
            name='day_to_visit',
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.transport'),
        ),
        migrations.AddField(
            model_name='route',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='routeclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='sequence',
            field=models.PositiveIntegerField(help_text='Default sequence order for this client'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('transportation', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['weekday'], name='routes_route_weekday_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='routes_route_active_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['transportation', 'weekday'], name='routes_transport_weekday_idx'),
        ),
        migrations.AddIndex(
            model_name='routeclient',
            index=models.Index(fields=['is_active'], name='routes_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='routeclient',
            index=models.Index(fields=['frequency'], name='routes_client_frequency_idx'),
        ),
        migrations.AddField(
            model_name='routeclientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_route_orders', to='clients.client'),
        ),
        migrations.AddField(
            model_name='routeclientorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='routeclientorder',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_client_orders', to='routes.route'),
        ),
        migrations.DeleteModel(
            name='RouteEmployee',
        ),
        migrations.AddIndex(
            model_name='routeclientorder',
            index=models.Index(fields=['visit_date'], name='routes_clientorder_date_idx'),
        ),
        migrations.AddIndex(
            model_name='routeclientorder',
            index=models.Index(fields=['is_completed'], name='routes_clientorder_comptd_idx'),
        ),
        migrations.AddIndex(
            model_name='routeclientorder',
            index=models.Index(fields=['route', 'visit_date'], name='routes_route_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routeclientorder',
            unique_together={('route', 'client', 'visit_date')},
        ),
    ]
