# Generated by Django 5.2 on 2025-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_routeclientorder_alter_routeemployee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
    ]
