# Generated by Django 5.2 on 2025-10-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_add_balance_credit_history'),
        ('core', '0004_alter_employee_options_alter_transport_options_and_more'),
        ('routes', '0005_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Ruta'),
        ),
        migrations.AlterField(
            model_name='route',
            name='transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.transport', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='route',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='monday', max_length=10, verbose_name='Día de la Semana'),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_routes', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='weekly', max_length=50),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='sequence',
            field=models.PositiveIntegerField(help_text='Default sequence order for this client', verbose_name='Ordinal'),
        ),
    ]
