# Generated by Django 5.2 on 2026-03-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nonworkingday'),
        ('routes', '0006_alter_route_created_at_alter_route_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='core.transport', verbose_name='Vehículo'),
        ),
    ]
