# Generated by Django 5.2 on 2026-03-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_route_transportation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
    ]
