# Generated by Django 5.2 on 2026-03-12 15:52

import datetime
import django.core.validators
from django.db import migrations, models


LEGACY_FREQUENCY_TO_INTERVAL = {
    'weekly': 1,
    'biweekly': 2,
    'monthly': 4,
}

WEEKDAY_TO_INDEX = {
    'monday': 0,
    'tuesday': 1,
    'wednesday': 2,
    'thursday': 3,
    'friday': 4,
    'saturday': 5,
    'sunday': 6,
}


def _align_to_route_weekday(base_date, route_weekday):
    target_weekday = WEEKDAY_TO_INDEX.get(route_weekday)
    if target_weekday is None:
        return base_date
    delta = (base_date.weekday() - target_weekday) % 7
    return base_date - datetime.timedelta(days=delta)


def migrate_frequency_to_interval(apps, schema_editor):
    RouteClient = apps.get_model('routes', 'RouteClient')
    today = datetime.date.today()

    for route_client in RouteClient.objects.select_related('route').all():
        legacy_frequency = getattr(route_client, 'frequency', 'weekly') or 'weekly'
        route_weekday = getattr(route_client.route, 'weekday', None) if route_client.route_id else None

        route_client.interval_weeks = LEGACY_FREQUENCY_TO_INTERVAL.get(legacy_frequency, 1)
        route_client.anchor_date = _align_to_route_weekday(today, route_weekday)
        route_client.save(update_fields=['interval_weeks', 'anchor_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_alter_address_type'),
        ('routes', '0008_alter_route_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routeclient',
            name='routes_client_frequency_idx',
        ),
        migrations.AddField(
            model_name='routeclient',
            name='anchor_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha base para calcular cada cuántas semanas corresponde la visita.', verbose_name='Fecha de inicio de ciclo'),
        ),
        migrations.AddField(
            model_name='routeclient',
            name='interval_weeks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Frecuencia de visita expresada en semanas (1 a 4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Intervalo (semanas)'),
        ),
        migrations.RunPython(migrate_frequency_to_interval, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='routeclient',
            name='frequency',
        ),
        migrations.AddIndex(
            model_name='routeclient',
            index=models.Index(fields=['interval_weeks'], name='routes_client_interval_idx'),
        ),
    ]
