# Generated by Django 5.2 on 2026-04-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route_deleted_at_routeclient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeclient',
            options={'ordering': ['sequence'], 'verbose_name': 'Cliente en Ruta', 'verbose_name_plural': 'Clientes en Rutas'},
        ),
        migrations.AlterField(
            model_name='routeclient',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_clients', to='routes.route', verbose_name='Ruta'),
        ),
    ]
