# Generated by Django 5.2 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_routeclient_options_alter_routeclient_route'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeclient',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='routeclient',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True)),
                fields=('route', 'client'),
                name='routes_routeclient_active_uniq',
            ),
        ),
    ]
