# Generated by Django 5.2 on 2026-10-09 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_created_at_employee_deleted_at_and_more'),
        ('product', '0014_product_orden_remove_productclientprice_orden'),
        ('routes', '0012_replace_routeclient_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckInventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_date', models.DateField(verbose_name='Fecha de servicio')),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abierto en')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado en')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_truck_inventory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_truck_inventory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_inventory_sessions', to='routes.route', verbose_name='Ruta')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_inventory_sessions', to='core.transport', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Inventario de camioneta',
                'verbose_name_plural': 'Inventarios de camioneta',
                'ordering': ['-service_date', 'route__name'],
            },
        ),
        migrations.CreateModel(
            name='TruckInventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_loaded', models.PositiveIntegerField(default=0, verbose_name='Llenos cargados')),
                ('full_returned', models.PositiveIntegerField(default=0, verbose_name='Llenos regresados')),
                ('empty_returned', models.PositiveIntegerField(default=0, verbose_name='Envases vacíos regresados')),
                ('expected_sales', models.PositiveIntegerField(default=0, verbose_name='Ventas esperadas')),
                ('reported_sales', models.PositiveIntegerField(default=0, verbose_name='Ventas reportadas')),
                ('sales_difference', models.IntegerField(default=0, verbose_name='Diferencia de ventas')),
                ('missing_containers', models.IntegerField(default=0, verbose_name='Envases no recuperados')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_inventory_lines', to='product.product', verbose_name='Producto')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='routes.truckinventorysession', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Línea de inventario de camioneta',
                'verbose_name_plural': 'Líneas de inventario de camioneta',
                'ordering': ['product__name', 'product__presentation', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='truckinventorysession',
            index=models.Index(fields=['service_date'], name='routes_truck_inv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='truckinventorysession',
            index=models.Index(fields=['status'], name='routes_truck_inv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='truckinventorysession',
            index=models.Index(fields=['transportation', 'service_date'], name='routes_truck_inv_vehicle_idx'),
        ),
        migrations.AddConstraint(
            model_name='truckinventorysession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('route', 'transportation', 'service_date'), name='routes_truck_inv_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='truckinventoryline',
            index=models.Index(fields=['session', 'product'], name='routes_truck_line_prod_idx'),
        ),
        migrations.AddConstraint(
            model_name='truckinventoryline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'product'), name='routes_truck_line_active_uniq'),
        ),
    ]
