# Generated by Django 5.2 on 2025-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_address_note_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Queretaro', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Queretaro', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='76000', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdata',
            name='metodo_pago',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('bank_transfer', 'Transferencia Bancaria'), ('balance', 'Saldo'), ('credit', 'Crédito'), ('other', 'Otro')], default='other', max_length=255),
        ),
    ]
