# Generated by Django 5.2 on 2025-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_address_city_alter_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='rfc',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='clients_address_city_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='clients_address_state_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['active'], name='clients_address_active_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdata',
            index=models.Index(fields=['rfc'], name='clients_billing_rfc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_client_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['active'], name='clients_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type'], name='clients_client_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='clients_contact_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='clients_contact_email_idx'),
        ),
    ]
