# Generated by Django 5.2 on 2025-09-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_billingdata_rfc_alter_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBillingFrecuency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('other', 'Otro')], default='other', max_length=50)),
                ('billing_date', models.CharField(choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('number_of_week_day', 'Número de semana y día'), ('other', 'Otro')], default='specific_date', max_length=50)),
                ('specific_day', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_frecuency', related_query_name='client_billing_frecuency', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['frequency'], name='clients_billing_frequency_idx'), models.Index(fields=['billing_date'], name='clients_billing_date_idx')],
            },
        ),
    ]
