# Generated by Django 5.2 on 2025-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientbillingfrecuency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientbillingfrecuency',
            options={'verbose_name': 'Billing Frequency', 'verbose_name_plural': 'Billing Frequencies'},
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about billing schedule', null=True),
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='occurrence',
            field=models.IntegerField(blank=True, choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer'), (4, 'Cuarto'), (-1, 'Último')], help_text='Which occurrence in the month (1=First, -1=Last)', null=True),
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Day of the week (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='billing_date',
            field=models.CharField(choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('weekday_occurrence', 'Día específico de la semana'), ('other', 'Otro')], default='specific_date', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('other', 'Otro')], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='specific_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of the month (1-31)', null=True),
        ),
        migrations.AddIndex(
            model_name='clientbillingfrecuency',
            index=models.Index(fields=['is_active'], name='clients_billing_active_idx'),
        ),
    ]
