# Generated by Django 5.2 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_address_options_alter_billingdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto prepagado disponible para usar en pedidos', max_digits=10, verbose_name='Saldo a favor'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Máximo monto que el cliente puede deber', max_digits=10, verbose_name='Límite de crédito'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto actual que debe el cliente', max_digits=10, verbose_name='Deuda actual'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('billing', 'Facturación'), ('shipping', 'Envío'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='billing_date',
            field=models.CharField(choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('weekday_occurrence', 'Día específico de la semana'), ('other', 'Otro')], default='specific_date', max_length=50, verbose_name='Fecha de Facturación'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('other', 'Otro')], default='monthly', max_length=50, verbose_name='Frecuencia de Facturación'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el calendario de facturación', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='occurrence',
            field=models.IntegerField(blank=True, choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer'), (4, 'Cuarto'), (-1, 'Último')], help_text='Qué ocurrencia en el mes (1=Primera, -1=Última)', null=True, verbose_name='Ocurrencia'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='specific_day',
            field=models.PositiveIntegerField(blank=True, help_text='ía del mes (1-31)', null=True, verbose_name='Día Específico'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='ía de la semana (0=Lunes, 6=Domingo)', null=True, verbose_name='Día de la Semana'),
        ),
    ]
