# Generated by Django 5.2 on 2025-10-03 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_balance_client_credit_limit_and_more'),
        ('orders', '0007_alter_order_options'),
        ('payment', '0004_add_balance_credit_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Depósito'), ('payment', 'Pago con saldo'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste manual'), ('transfer_in', 'Transferencia recibida'), ('transfer_out', 'Transferencia enviada'), ('correction', 'Corrección')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Posterior')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_transactions', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Orden relacionada')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment', verbose_name='Pago relacionado')),
                ('transfer_to_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transfers_received', to='clients.client', verbose_name='Cliente destino (transferencia)')),
            ],
            options={
                'verbose_name': 'Transacción de Saldo',
                'verbose_name_plural': 'Transacciones de Saldo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='balance_tx_client_date_idx'), models.Index(fields=['transaction_type'], name='balance_tx_type_idx'), models.Index(fields=['created_at'], name='balance_tx_date_idx'), models.Index(fields=['reference_order'], name='balance_tx_order_idx'), models.Index(fields=['reference_payment'], name='balance_tx_payment_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra a crédito'), ('payment', 'Pago de deuda'), ('adjustment', 'Ajuste manual'), ('limit_change', 'Cambio de límite'), ('interest', 'Interés aplicado'), ('fee', 'Cargo adicional'), ('forgiveness', 'Condonación'), ('correction', 'Corrección')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('debt_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deuda Anterior')),
                ('debt_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deuda Posterior')),
                ('credit_limit_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite Anterior')),
                ('credit_limit_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite Posterior')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Orden relacionada')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment', verbose_name='Pago relacionado')),
            ],
            options={
                'verbose_name': 'Transacción de Crédito',
                'verbose_name_plural': 'Transacciones de Crédito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='credit_tx_client_date_idx'), models.Index(fields=['transaction_type'], name='credit_tx_type_idx'), models.Index(fields=['created_at'], name='credit_tx_date_idx'), models.Index(fields=['reference_order'], name='credit_tx_order_idx'), models.Index(fields=['reference_payment'], name='credit_tx_payment_idx')],
            },
        ),
    ]
