# Generated by Django 5.2 on 2025-10-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_add_balance_credit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('payment', 'Pago con saldo'), ('added_in_order', 'Saldo agregado en venta'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste manual'), ('transfer_in', 'Transferencia recibida'), ('transfer_out', 'Transferencia enviada'), ('correction', 'Corrección')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
