# Generated by Django 5.2 on 2025-10-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_balancetransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='description',
        ),
    ]
