# Generated by Django 5.2 on 2025-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_balancetransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_pay_with_credit',
            field=models.BooleanField(default=True, help_text='Si está deshabilitado, el cliente no podrá usar crédito para pagos cuando su saldo disponible sea 0', verbose_name='Puede pagar con crédito'),
        ),
        migrations.AddField(
            model_name='client',
            name='requires_note_for_credit',
            field=models.BooleanField(default=False, help_text='Si está habilitado, se requerirá una nota obligatoria al realizar pagos con crédito', verbose_name='Requiere nota para crédito'),
        ),
    ]
