# Generated by Django 5.2 on 2025-10-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_can_pay_with_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='requires_note_for_credit',
            field=models.BooleanField(default=False, help_text='Si está habilitado, se requerirá una justificación obligatoria al realizar pagos con crédito', verbose_name='Requiere justificación para crédito'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Compra a crédito'), ('payment', 'Pago de deuda'), ('payment_from_balance', 'Pago con Saldo'), ('adjustment', 'Ajuste manual'), ('limit_change', 'Cambio de límite'), ('interest', 'Interés aplicado'), ('fee', 'Cargo adicional'), ('forgiveness', 'Condonación'), ('correction', 'Corrección')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.CreateModel(
            name='ClientCreditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('max_payment_days', models.PositiveIntegerField(default=30, verbose_name='Días máximos para pagar')),
                ('first_notification_days', models.PositiveIntegerField(default=5, verbose_name='Días antes del vencimiento para la primera notificación')),
                ('second_notification_days', models.PositiveIntegerField(default=2, verbose_name='Días antes del vencimiento para la segunda notificación')),
                ('overdue_notification_days', models.PositiveIntegerField(default=1, verbose_name='Días después del vencimiento para notificación de morosidad')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_config', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
