# Generated by Django 5.2 on 2025-11-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_client_requires_note_for_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_link',
            field=models.CharField(blank=True, help_text='Enlace a Google Maps u otro servicio de mapas', max_length=255, null=True, verbose_name='Enlace de dirección'),
        ),
    ]
