# Generated by Django 5.2 on 2025-12-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_address_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='requires_billing',
            field=models.BooleanField(default=False, help_text='Indica si el cliente necesita facturación formal', verbose_name='Requiere facturación'),
        ),
    ]
