# Generated by Django 5.2 on 2025-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_client_requires_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
        migrations.RemoveField(
            model_name='billingdata',
            name='uso_cfdi',
        ),
        migrations.AddField(
            model_name='address',
            name='exterior_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Exterior'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='address',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delegación o Municipio'),
        ),
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Interior'),
        ),
        migrations.AlterField(
            model_name='billingdata',
            name='metodo_pago',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('bank_transfer', 'Transferencia Bancaria'), ('balance', 'Saldo'), ('credit', 'Crédito'), ('other', 'Otro')], default='other', max_length=255, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('corporate', 'Corporativo'), ('branch', 'Sucursal')], default='branch', max_length=50, verbose_name='Tipo de cliente'),
        ),
    ]
