# Generated by Django 5.2 on 2025-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_address_number_remove_billingdata_uso_cfdi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='curp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='billingdata',
            name='uso_cfdi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Uso de CFDI'),
        ),
    ]
