# Generated by Django 5.2 on 2025-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_billingdata_curp_billingdata_regimen_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Domicilio', 'verbose_name_plural': 'Domicilios'},
        ),
        migrations.RemoveField(
            model_name='billingdata',
            name='regimen_fiscal',
        ),
        migrations.RemoveField(
            model_name='billingdata',
            name='uso_cfdi',
        ),
        migrations.AddField(
            model_name='client',
            name='max_payment_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Cantidad días para pagar'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('billing', 'Fiscal'), ('shipping', 'Ubicacion fisica'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Tipo'),
        ),
    ]
