# Generated by Django 5.2 on 2025-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='max_payment_days',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Cantidad días para pagar'),
        ),
    ]
