# Generated by Django 5.2 on 2025-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_client_max_payment_days'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='clients_address_city_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['municipality'], name='clients_address_munic_idx'),
        ),
    ]
