# Generated by Django 5.2 on 2026-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_address_clients_address_city_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='frequency',
            field=models.CharField(choices=[('when_delivery', 'Contra entrega'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='monthly', max_length=50, verbose_name='Frecuencia de Facturación'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='specific_day',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes (1-31)', null=True, verbose_name='Día Específico'),
        ),
    ]
