# Generated by Django 5.2 on 2026-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_clientbillingfrecuency_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_cancellation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_first_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_second_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
