# Generated by Django 5.2 on 2026-01-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_client_last_cancellation_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='max_payment_days',
        ),
        migrations.AlterField(
            model_name='client',
            name='corporate',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'corporate'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clients.client', verbose_name='Cliente corporativo'),
        ),
    ]
