# Generated by Django 5.2 on 2026-01-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_remove_client_max_payment_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='clients.address'),
        ),
    ]
