# Generated by Django 5.2 on 2026-01-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_billingdata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='clients.address'),
        ),
    ]
