# Generated by Django 5.2 on 2026-01-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_billingdata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billingdata',
            name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.client', verbose_name='Cliente'),
        ),
    ]
