# Generated by Django 5.2 on 2026-01-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_billingdata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='clients.client'),
        ),
    ]
