# Generated by Django 5.2 on 2026-01-25 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_billingdata_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_frecuency', related_query_name='client_billing_frecuency', to='clients.client'),
        ),
    ]
