# Generated by Django 5.2 on 2026-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_clientbillingfrecuency_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientbillingfrecuency',
            options={'verbose_name': 'Frecuencia de Facturación', 'verbose_name_plural': 'Frecuencias de Facturación'},
        ),
        migrations.AddField(
            model_name='clientbillingfrecuency',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Facturación'),
        ),
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='billing_date',
            field=models.CharField(choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('weekday_occurrence', 'Día específico de la semana')], default='specific_date', max_length=50, verbose_name='Fecha de Facturación'),
        ),
    ]
