# Generated by Django 5.2 on 2026-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_alter_clientbillingfrecuency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbillingfrecuency',
            name='billing_date',
            field=models.CharField(blank=True, choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('weekday_occurrence', 'Día específico de la semana')], default='specific_date', max_length=50, null=True, verbose_name='Fecha de Facturación'),
        ),
    ]
