# Generated by Django 5.2 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_alter_clientbillingfrecuency_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nombre del cliente'),
        ),
        migrations.DeleteModel(
            name='ClientBillingFrecuency',
        ),
    ]
