# Generated by Django 5.2 on 2026-02-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_alter_client_name_delete_clientbillingfrecuency'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_override_enabled',
            field=models.BooleanField(default=False, help_text='Si está habilitado, la sucursal usará sus propios datos de facturación en lugar de heredar del corporativo', verbose_name='Usar datos propios de facturación'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('billing', 'Fiscal'), ('shipping', 'Ubicacion fisica'), ('other', 'Otro')], default='shipping', max_length=50, verbose_name='Tipo'),
        ),
    ]
