# Generated by Django 5.2 on 2026-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_add_billing_override_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(default='Querétaro', max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(default='Querétaro', max_length=100, verbose_name='Delegación o Municipio'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Querétaro', max_length=100, verbose_name='Estado'),
        ),
    ]
