# Generated by Django 5.2 on 2026-02-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_alter_address_locality_alter_address_municipality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='note',
        ),
    ]
