# Generated by Django 5.2 on 2026-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_remove_address_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('billing', 'Fiscal'), ('delivery', 'Ubicacion fisica'), ('other', 'Otro')], default='delivery', max_length=50, verbose_name='Tipo'),
        ),
    ]
