# Generated by Django 5.2 on 2026-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_alter_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('billing', 'Fiscal'), ('delivery', 'Entrega'), ('other', 'Otro')], default='delivery', max_length=50, verbose_name='Tipo'),
        ),
    ]
