# Generated by Django 5.2 on 2026-03-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_alter_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID del cliente en sistemas externos (ERP, CRM, etc.)', max_length=100, null=True, verbose_name='ID externo'),
        ),
    ]
