# Generated by Django 5.2 on 2026-04-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_address_created_at_alter_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('deleted_at', 'name')},
        ),
    ]
