# Generated by Django 5.2 on 2026-04-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_alter_client_name_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
    ]
