# Generated by Django 5.2 on 2026-04-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(default='Querétaro', max_length=100, verbose_name='Colonia'),
        ),
    ]
