# Generated by Django 5.2 on 2026-06-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_rename_billingdata_to_invoicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditconfig',
            name='max_payment_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Días naturales máximos para pagar'),
        ),
    ]
