# Generated by Django 5.2 on 2026-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_remove_client_requires_note_for_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('payment', 'Pago con saldo'), ('added_in_order', 'Saldo agregado en venta'), ('payment_reversal', 'Reversión de pago con saldo'), ('added_in_order_reversal', 'Reversión de saldo agregado en venta'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste manual'), ('transfer_in', 'Transferencia recibida'), ('transfer_out', 'Transferencia enviada'), ('correction', 'Corrección')], max_length=30, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Compra a crédito'), ('payment', 'Pago de deuda'), ('payment_from_balance', 'Pago con Saldo'), ('purchase_reversal', 'Reversión de compra a crédito'), ('payment_reversal', 'Reversión de pago de deuda'), ('adjustment', 'Ajuste manual'), ('limit_change', 'Cambio de límite'), ('interest', 'Interés aplicado'), ('fee', 'Cargo adicional'), ('forgiveness', 'Condonación'), ('correction', 'Corrección')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
