# Generated by Django 5.2 on 2026-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_replace_billing_override_with_credit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la transacción. Si no se proporciona, se usará la fecha y hora actual.', null=True, verbose_name='Fecha de transacción'),
        ),
    ]
