# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_balancetransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='date',
            field=models.DateField(
                blank=True,
                help_text='Fecha de la transacción. Si no se proporciona, se usará la fecha de creación.',
                null=True,
                verbose_name='Fecha de transacción',
            ),
        ),
    ]
