# Generated by Codex on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_credittransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='confirmation_delivery_method',
            field=models.CharField(
                choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')],
                default='whatsapp',
                help_text='Canal preferido para enviar confirmaciones de pedido',
                max_length=20,
                verbose_name='Canal de confirmación',
            ),
        ),
    ]
