server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://water_delivery_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Only keep containers that belong to this project via your label
      - source_labels: ['__meta_docker_container_label_project']
        regex: water-delivery
        action: keep

      # Attach useful labels (these become queryable in Grafana)
      - source_labels: ['__meta_docker_container_label_project']
        target_label: project
      - source_labels: ['__meta_docker_container_label_environment']
        target_label: environment
      - source_labels: ['__meta_docker_container_label_service']
        target_label: service
      - source_labels: ['__meta_docker_container_name']
        target_label: container
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id

      # Where to read the JSON log files from:
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log