# Generated by Django 5.2 on 2026-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clienttenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienttenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
