# Generated by Django 5.2 on 2025-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
    ]
