# Generated by Django 5.2 on 2025-10-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employee',
            new_name='owner',
        ),
    ]
