# Generated by Django 5.2 on 2025-10-28 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_employee_order_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('child_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_as_child', to='orders.order', verbose_name='Orden Derivada')),
                ('source_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_as_source', to='orders.order', verbose_name='Orden Original')),
                ('split_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dividido por')),
            ],
            options={
                'verbose_name': 'División de Orden',
                'verbose_name_plural': 'Divisiones de Órdenes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_order'], name='ordersplit_source_idx'), models.Index(fields=['child_order'], name='ordersplit_child_idx')],
            },
        ),
    ]
