# Generated by Django 5.2 on 2025-10-29 15:09

from django.db import migrations


def fix_order_status_values(apps, schema_editor):
    """
    Fix order status values that were incorrectly saved as 'OrderStatus.COMPLETED'
    instead of just 'COMPLETED'
    """
    Order = apps.get_model('orders', 'Order')
    
    # Fix any orders with the incorrect format
    for order in Order.objects.all():
        if order.status.startswith('OrderStatus.'):
            # Extract the actual status value (e.g., 'COMPLETED' from 'OrderStatus.COMPLETED')
            correct_status = order.status.replace('OrderStatus.', '')
            order.status = correct_status
            order.save(update_fields=['status'])


def reverse_fix(apps, schema_editor):
    """
    Reverse migration - no action needed as we can't reliably revert to incorrect format
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_ordersplit'),
    ]

    operations = [
        migrations.RunPython(fix_order_status_values, reverse_fix),
    ]
