# Generated by Django 5.2 on 2026-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_fix_order_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado a la orden (en la moneda del total)', max_digits=10, verbose_name='Descuento'),
        ),
    ]
