# Generated by ChatGPT on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de los productos antes de descuentos', max_digits=10, verbose_name='Subtotal'),
        ),
    ]
