# Generated by Django 5.2 on 2026-03-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_subtotal_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
