# Generated by Django 5.2 on 2026-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderproduct_created_at_orderproduct_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', help_text='Tipo de orden para diferenciar entre órdenes a credito y órdenes de contado', max_length=50, verbose_name='Tipo de Orden'),
        ),
    ]
