# Generated by Django 5.2 on 2026-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', help_text='Tipo de orden para diferenciar entre órdenes a credito y órdenes de contado', max_length=50, null=True, verbose_name='Tipo de Orden'),
        ),
    ]
