# Generated by Django 5.2 on 2026-09-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_cancellation_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Metodo de envio')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('pdf_url', models.CharField(max_length=500, verbose_name='PDF privado')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono de contacto')),
                ('contact_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto de contacto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Recibo de pedido',
                'verbose_name_plural': 'Recibos de pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method'], name='orders_receipt_method_idx'), models.Index(fields=['sent_at'], name='orders_receipt_sent_idx')],
            },
        ),
    ]
