# Generated by Django 5.2 on 2026-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceipt',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='orderreceipt',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='orderreceipt',
            name='method',
            field=models.CharField(choices=[('none', 'Sin envio'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Metodo de envio'),
        ),
    ]
