# Generated by Django 5.2 on 2025-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingrecord_folio_alter_billingrecord_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='folio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Folio'),
        ),
    ]
