# Generated by Django 5.2 on 2026-02-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingfrequencyreport'),
        ('clients', '0031_alter_client_name_delete_clientbillingfrecuency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBillingFrecuency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('when_delivery', 'Contra entrega'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='monthly', max_length=50, verbose_name='Frecuencia de Facturación')),
                ('billing_date', models.CharField(blank=True, choices=[('specific_date', 'Fecha específica del mes'), ('last_day', 'Último día del mes'), ('first_day', 'Primer día del mes'), ('weekday_occurrence', 'Día específico de la semana')], max_length=50, null=True, verbose_name='Fecha de Facturación')),
                ('specific_day', models.PositiveIntegerField(blank=True, help_text='Día del mes (1-31)', null=True, verbose_name='Día Específico')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='ía de la semana (0=Lunes, 6=Domingo)', null=True, verbose_name='Día de la Semana')),
                ('occurrence', models.IntegerField(blank=True, choices=[(1, 'Primer'), (2, 'Segundo'), (3, 'Tercer'), (4, 'Cuarto'), (-1, 'Último')], help_text='Qué ocurrencia en el mes (1=Primera, -1=Última)', null=True, verbose_name='Ocurrencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el calendario de facturación', null=True, verbose_name='Notas')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Facturación')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_frecuency', related_query_name='client_billing_frecuency', to='clients.client')),
            ],
            options={
                'verbose_name': 'Frecuencia de Facturación',
                'verbose_name_plural': 'Frecuencias de Facturación',
                'db_table': 'clients_clientbillingfrecuency',
                'indexes': [models.Index(fields=['frequency'], name='clients_billing_frequency_idx'), models.Index(fields=['billing_date'], name='clients_billing_date_idx'), models.Index(fields=['is_active'], name='clients_billing_active_idx')],
            },
        ),
    ]
