# Generated by Django 5.2 on 2026-04-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_rename_billingfrequencyreport_to_invoicefrequencyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='emmited_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
    ]
