# Generated by Django 5.2 on 2026-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_rename_billingfrequencyreport_to_invoicefrequencyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='auto_amount',
            field=models.BooleanField(default=False, help_text='Si está activo, el monto se calcula automáticamente como la suma de los pedidos vinculados.', verbose_name='Monto automático'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='emmited_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
    ]
