# Generated by Django 5.2 on 2026-05-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_amount_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
    ]
