# Generated by Django 5.2 on 2026-05-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_invoice_emmited_at'),
        ('billing', '0018_remove_invoice_description'),
    ]

    operations = [
    ]
