# Generated by Django 5.2 on 2026-05-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_merge_20260513_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date'], 'verbose_name': 'Facturacion', 'verbose_name_plural': 'Facturas'},
        ),
    ]
