# Generated by Django 5.2 on 2026-07-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='folio',
            field=models.CharField(max_length=100, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='identifier',
            field=models.CharField(max_length=100, verbose_name='Serie'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('identifier', 'folio')},
        ),
    ]
