# Generated by Django 5.2 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_relax_obsolete_monthly_ordinal_day_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada')],
                db_index=True,
                default='ACTIVE',
                max_length=10,
                verbose_name='Estado',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Fecha de cancelación',
            ),
        ),
    ]
