# Generated by Django 5.2 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_invoice_cancellation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Borrador'),
                    ('ACTIVE', 'Activa'),
                    ('CANCELLED', 'Cancelada'),
                ],
                db_index=True,
                default='ACTIVE',
                max_length=10,
                verbose_name='Estado',
            ),
        ),
    ]
